### ISSUE TITLE
error: definition of implicitly-declared 'File::~File()'

### ISSUE THREAD

**Issue by lischetzke** [adafruit/SD#16]
> File.cpp:46: error: definition of implicitly-declared 'File::~File()'
>  File::~File(void) {

> exit status 1
> definition of implicitly-declared 'File::~File()'

Every time I try to compile my code, this error appears

**Comment by scottpidzarko** [comment]
Did you manage to work around this @lischetzke ?

**Comment by lischetzke** [comment]
No, but I don't concern it anymore, so no need for me to solve this problem (Issue is already too old).
