### ISSUE TITLE
SD.begin() doesn't work with Adafruit SD Breakout board

### ISSUE THREAD

**Issue by basti2k** [adafruit/SD#18]
- Arduino board:  Arduino Mega 2560

- Arduino IDE version (found in Arduino -> About Arduino menu):  1.8.0

// TESTCODE
#include <SPI.h>
#include <SD.h>

void setup()
{
   Serial.begin(57600);
   if(!SD.begin(53))
   {
      Serial.print(F("SD CARD ERROR"));
      while(1);
   }
   Serial.print(F("SD CARD OK"));
   while(1);
}

void loop()
{
}

The Code works with the "SD by Arduino, Sparkfun" Lib version 1.0.9 but not with the version 1.1.0

**Tested Examples from IDE[1]:**
Example | SD 1.0.9 | SD 1.1.0 |
+++++++++++++++++++
Cardinfo | works | works |
Datalogger | works | "Card faild"
Dumpfile | works | "Card faild"
Files | works | "initialization failed!"
listfiles | works | "initialization failed!"
readwrite | works | "initialization failed!"

[1] - Set the CS-PIN to 53

**Comment by ladyada** [comment]
this library fork is being archived - please use the SdFat Library instead (its much better) for any advanced SD card needs!
