### ISSUE TITLE
SoftSpi Not Working on DUE Board

### ISSUE THREAD

**Issue by whereismymndd** [adafruit/SD#19]
IDE Version : 1.6.9
Board Type: Due

The software spi not working for DUE board, connected SD card.
 I changed 
```
#if defined(__arm__) // Arduino Due Board follows

#ifndef Sd2PinMap_h
#define Sd2PinMap_h

#include <Arduino.h>

uint8_t const SS_PIN = 10;
uint8_t const MOSI_PIN = 11;
uint8_t const MISO_PIN = 12;
uint8_t const SCK_PIN = 13;

#endif // Sd2PinMap_h
```
But still same, i using CardInfo Example for test, SS pin is 10 and speed is SPI_QUARTER_SPEED.
The SD card Working with Hardware SPI. But i need SoftSpi for these LCD shields.

**Comment by ladyada** [comment]
this library fork is being archived - please use the SdFat Library instead (its much better) for any advanced SD card needs!
