### ISSUE TITLE
SD.Begin(int, int. int. int) can only be called once.

### ISSUE THREAD

**Issue by davidstellini** [adafruit/SD#7]
Demo code:
# include <SD.h>

void setup()
{
  Serial.begin(115200);
  Serial.println("Starting...");
 if (!SD.begin(53,2,4,3)) {  // chipSel, mosi, miso, sck
    Serial.println(F("initialization failed!"));
  } else {
    Serial.println(F("initialization done."));
  }

   if (!SD.begin(53,2,4,3)) {  // chipSel, mosi, miso, sck
    Serial.println(F("initialization failed!"));
  } else {
    Serial.println(F("initialization done."));
  }
}

void loop(void) {

}

Output:

Starting...
initialization done.
initialization failed!

Expected output:
Starting...
initialization done.
initialization done.

**Comment by dariosalvi78** [comment]
Hi,

this is definitely a bug, in fact, if you have more than one SPI device you must call begin() each time you need to switch from another device to the SD card.
I have had the problem myself.

Solution:
in the file named SD.cpp, in function begin() (line 337) add this instruction before the return statement:
`if(root.isOpen()) root.close();`

this has solved the problem for me.

**Comment by ladyada** [comment]
this library fork is being archived - please use the SdFat Library instead (its much better) for any advanced SD card needs!
